src/Entity/Cat.php
<?php

namespace App\Entity;

use App\Entity\Traits\HasIdTrait;
use App\Entity\Traits\HasNameTrait;
use App\Repository\CatRepository;
use DateTime;
use DateTimeImmutable;
use DateTimeInterface;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\Validator\Constraints as Assert;
use Vich\UploaderBundle\Mapping\Annotation as Vich;

/**
 * @ORM\Entity(repositoryClass=CatRepository::class)
 * @Vich\Uploadable()
 */
class Cat
{

    use HasNameTrait;
    use HasIdTrait;


    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Picture::class, mappedBy="cat", orphanRemoval=true, cascade={"persist"})
     */
    private $pictures;

    /**
     * @Assert\All({
     *   @Assert\Image(mimeTypes="image/jpeg")
     * })
     */
    private $pictureFiles;

    /**
     * @ORM\ManyToOne(targetEntity=Adoption::class, inversedBy="cats")
     */
    private $adoption;


    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $sexe;

    /**
     * @ORM\Column(type="boolean")
     */
    private $taken;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="cats")
     */
    private $user;

    /**
     * @ORM\Column(type="date", nullable=true)
     */
    private $birthDate;

    /**
     * @ORM\Column(type="datetime")
     */
    private $createdAt;

    /**
     * @ORM\Column(type="datetime")
     */
    private $updatedAt;



    public function __construct()
    {
        $this->taken = false;
        $this->pictures = new ArrayCollection();
        $this->sexe = false;
        //$http_response_header
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getBirthDate(): ?DateTimeInterface
    {
        return $this->birthDate;
    }

    public function setBirthDate(?DateTimeInterface $birthDate): self
    {
        $this->birthDate = $birthDate;

        return $this;
    }

    public function getAge(): ?int
    {
        if (empty($this->getBirthDate())) {
            return null;
        }

        $now = new DateTime();

        $diff = $this->getBirthDate()->diff($now, true);

        return $diff->y;
    }

    /**
     * @return Collection|Picture[]
     */
    public function getPictures(): Collection
    {
        return $this->pictures;
    }

    public function addPicture(Picture $picture): self
    {
        if (!$this->pictures->contains($picture)) {
            $this->pictures[] = $picture;
            $picture->setCat($this);
        }

        return $this;
    }

    public function removePicture(Picture $picture): self
    {
        if ($this->pictures->removeElement($picture)) {
            // set the owning side to null (unless already changed)
            if ($picture->getCat() === $this) {
                $picture->setCat(null);
            }
        }

        return $this;
    }

    public function getAdoption(): ?Adoption
    {
        return $this->adoption;
    }

    public function setAdoption(?Adoption $adoption): self
    {
        $this->adoption = $adoption;

        return $this;
    }


    public function getSexe(): ?bool
    {
        return $this->sexe;
    }

    public function setSexe(?bool $sexe): self
    {
        $this->sexe = $sexe;

        return $this;
    }

    public function getTaken(): ?bool
    {
        return $this->taken;
    }

    public function setTaken(bool $taken): self
    {
        $this->taken = $taken;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getPictureFiles()
    {
        return $this->pictureFiles;
    }

    /**
     * @param mixed $pictureFiles
     * @return Cat
     */
    public function setPictureFiles($pictureFiles): self
    {
       /* foreach($pictureFiles as $pictureFile) {
            $picture = new Picture();
            $picture->setImageFile($pictureFile);
            $this->addPicture($picture);
        }*/
        $this->pictureFiles = $pictureFiles;
        return $this;
    }

    public function __toString()
    {
        return $this->getName();
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }



}

src/Controller/DefaultController.php
<?php

namespace App\Controller;


use App\Entity\Adoptant;
use App\Entity\Adoption;
use App\Entity\Contact;

use App\Entity\ContactPreAdoption;
use App\Form\ContactFormType;
use App\Form\ContactType;
use App\Repository\AdoptionRepository;
use App\Repository\AssociationRepository;

use App\Notification\ContactNotification;
use Doctrine\ORM\EntityManagerInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Mailer\MailerInterface;
use Symfony\Component\Mime\Email;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Form\FormTypeInterface;


class DefaultController extends AbstractController
{

    private $mailer;

    public function __construct(MailerInterface $mailer)
    {
        $this->mailer = $mailer;
    }
    /**
     * @Route("/", name="default_index")
     * @param AdoptionRepository $adoptionRepository
     * @return Response
     */
    public function index(AdoptionRepository $adoptionRepository, AssociationRepository $associationRepository): Response
    {

       $adoptions = $adoptionRepository->findNotTaken(5, 'updatedAt');
       $associations = $associationRepository->findAll();

        return $this->render('default/index.html.twig', [
            'adoptions' => $adoptions,
            'associations' => $associations
        ]);
    }

    /**
     * @Route("/contact", name="default_contact")
     * @Route("/contact/{id}", name="default_contact_for_adoption")
     * @throws \Symfony\Component\Mailer\Exception\TransportExceptionInterface
     */
    public function contact(Request $request, EntityManagerInterface $entityManager, Adoption $adoption = null): Response
    {

        $this->denyAccessUnlessGranted('ROLE_USER'); // like if we put annotation @IsGranted but we can define roles redirection


        $contact = new Contact();

        $contact->setAdoption($adoption);

        $form = $this->createForm(ContactFormType::class, $contact);

        $form->handleRequest($request);

        if($form->isSubmitted() && $form->isValid())
        {
            /*$notification->notify($contact);*/
            /*$mailer->sendEmail();*/

            //$email = (new Email())
            //    ->from('docteurfutur@gmail.com')
                //->from($contact->get('email'))
            //    ->to('docteurfutur@gmail.com')
                //->cc('cc@example.com')
                //->bcc('bcc@example.com')
           //     ->replyTo($contact->getEmail(''))
                //->priority(Email::PRIORITY_HIGH)
                //->subject('Time for Symfony Mailer!')
            //    ->text('Sending emails is fun again!')
             //   ->getHtmlBody($this->render('emails/contact.html.twig', [
            //        'contact' => $contact
            //    ]), 'text/html');
            //$this->mailer->send();
                //->html('<p>See Twig integration for better HTML integration!</p>');
            /*
                //->from('noreply@agence.fr')
                //->to('contact@anima.fr')
                //->replyTo($contact->getEmail());*/
                /**/

            


            //$mailer->send($email);

            //$context = [
              //  'adoption' => $adoption,
                //'mail' => $contact->get('email')->getData(),
                //'message' => $contact->get('message')->getData()
            //];

            //$mail->send($contact->get('email')->getData(), $annonce->getUsers()->getEmail(), 'Contact au sujet de votre annonce "' . $annonce->getTitle() . '"', 'contact_annonce', $context);

            // On confirme et on redirige
            //$this->addFlash('message', 'Votre e-mail a bien été envoyé');
            //return $this->redirectToRoute('annonces_details', ['slug' => $annonce->getSlug()]);
        //}


            $entityManager->persist($contact);
            $entityManager->flush();

            $this->addFlash('success', 'Votre demande de pré-adoption a bien été envoyé, merci !');

            return $this->redirectToRoute('default_contact');

           /* $this->addFlash('success', 'Votre message a bien été envoyé');

            return $this->redirectToRoute('default_index');*/
        }

        return $this->render('default/contact.html.twig', [
            'form' => $form->createView(),
        ]);


        /*        $contact = new Contact();
                $contact->setAdoption($adoption);

                $form = $this->createForm(ContactType::class, $contact);

                $form->handleRequest($request);

                if ($form->isSubmitted() && $form->isValid()) {
                    $entityManager->persist($contact);
                    $entityManager->flush();

                    $this->addFlash('success', 'msg envoyé');

                    return $this->redirectToRoute('default_contact');
                }

                return $this->render('default/contact.html.twig', [
                    'form' => $form->createView(),
                ]);*/
    }

    /**
     * @Route("/conditions", name="default_conditions")
     */
    public function conditions(): Response
    {
        return $this->render('default/conditions.html.twig', [
            'controller_name' => 'DefaultController',
        ]);
    }

    /**
     * @Route("/preadoption", name="default_preadoption")
     */
    public function preadoption(Request $request, EntityManagerInterface $entityManager, Adoption $adoption = null): Response
    {
        $preadoption = new ContactPreAdoption();
        $preadoption->setAdoption($adoption);

        $form = $this->createForm(ContactPreAdoption::class, $preadoption);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($preadoption);
            $entityManager->flush();

            $this->addFlash('success', 'Votre demande d\'adoption a bien été envoyée, Nous vous contacterons au plus vite');

            return $this->redirectToRoute('default_preadoption');
        }

        return $this->render('default/preadoption.html.twig', [
            'form' => $form->createView(),
        ]);
    }
}

templates/default/conditions.html.twig
{% extends '/base.html.twig' %}

{% block title %}Hello DefaultController!
{% endblock %}

{% block body %}


    <nav>
        <h1>FORMALITÉS</h1>

            <a href="#intro">Tarifs</a>
            <a href="#prices">Services</a>
            <a href="#concept">Conditions</a>
        <h2>FRAIS D’ADOPTION</h2>
    </nav>

    <main>
        <section id="intro">
            <img src="images/logo-vecr-anim-blue-transp.svg" alt="ANIMA Logo">
            <div>
                <h2>Ces tarifs, incluent:</h2>

                <ul>
                    <li>Les soins</li>
                    <li>La stérilisation ou castration (sauf chiots et chatons)</li>
                    <li>L’identification par puce électronique</li>
                    <li>Les vaccinations</li>
                    <li>Le déparasitage interne et externe</li>
                    <li>Les tests Leucose et F.I.V sont effectués pour les chats de plus de 6 mois.</li>
                    <li></li>
                    <li></li>
                </ul>
            </div>
        </section>

        <section id="prices">
            <h2>Tarifs d'adoption</h2>
            <ul>
                <li>
                    ​<picture>
                       {#<source srcset="images/home-header-Anima-img/chatons-psycho_61d46a6e8d925ecf4a5a25c62360bea8 1.svg" type="image/svg+xml">#}
                       <img src="images/1.svg" class="img-fluid img-thumbnail" alt="...">
                    </picture>
                    <h3>Chien</h3>
                    <hr>
                    <p>250<sup>euros</sup></p>
                    <p><a href="#intro">Ces tarifs, incluent:</a></p>
                </li>
                <li>
                    <h3>Chat</h3>
                    <hr>
                    <p>150<sup>euros</sup></p>
                    <p><a href="#intro">Ces tarifs, incluent:</a></p>
                </li>
            </ul>
        </section>

        <section id="concept">
            <div>
                <p>L’adoption d’un animal doit être un acte réfléchi, c’est pourquoi
                    nous vous demandons de remplir le formulaire de pré-adoption ci dessous.
                    Ce formulaire nous en apprend un petit peu plus sur vous ainsi que sur le
                    futur environnement de votre animal. Il vous permet également de vous poser les
                    bonnes questions avant la procédure d’adoption.
                </p>
                <a href="#" class="btn">Nous contacter</a>
            </div>
            <img src="images/logo-vecr-anim-blue-transp.svg" alt="ANIMA Logo">
        </section>
    </main>
</body>

</html>


{% endblock %}

templates/default/contact.html.twig
{% extends '/base.html.twig' %}

{% block title %}
    Nous contacter
{% endblock %}

{% block body %}

    <section id="contact" class="container shadow">

    {{ form_start(form) }}
    {{ form_row(form.subject, {
        label: 'Sujet de votre message',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.adoption, {
        label: 'Du temps, de l\'énergie, des caresse et papouilles, beaucoup d\'amour et de tendresse à offrir, vous voulez
                vous engager pour sauver un de nos rescapés, alors nous vous invitons choisir une de nos annonce ! (Vous devrez signer
                par la suite notre Charte Du Bien-Être Animal auquel vous devrez concentir pour pretendre devenir un heureux adoptant).',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.email, {
        label: 'Votre adresse email',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.message, {
        label: 'Votre message',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    <button type="submit" class="btn btn-info shadow">Envoyer</button>
    {{ form_end(form) }}

    <h2>
    Attention! Nous tenons à rappeler qu'une adoption est un acte qui doit être murement réfléchit,
    de nombreuses reponsabilités acompagnent...
    Vous donnez droit de visite à tous responsables de Anima, dans le cadre de l'accompagnement du placement
    de nos animaux rescapés.
    Anima se réserve le droit de reprendre un animal placé pour non respect de notre charte du bien être animal,
    dont vous aurez pris connaissance et signé (mauvais traitements, mal nourrit,
    mal souagné, ou vivant dans un espace non comforme).
    </h2>

    </section>

{% endblock %}

templates/default/index.html.twig
{% extends '/base.html.twig' %}

{% block title %}ANIMA{% endblock %}


    {% block body %}


{#<header id="entete">

    <div id="titre" class="container d-flex justify-content-between flex-column align-items-center">
        <h1 class="roboto black">protection animale</h1>
        <h2 class="rockwell">ANIMA, du latin “anima” signifie âme, souffle.
                D’ou provient le terme ANIMAL.</h2>
        <a class="shadow" href="#concept">Découvrir</a>
    </div>
</header>#}

       <body>
            <main>
                {#​<picture>
                    <source srcset="images/home-header-Anima-img/chatons-psycho_61d46a6e8d925ecf4a5a25c62360bea8 1.svg" type="image/svg+xml">#}
                    {#<img src="images/logo-anima/logo-vector.svg" class="img-fluid img-thumbnail" alt="...">
                </picture>#}
                {#<img class="shape img-fluid text-center" src="images/logo-anima/logo-vector.svg" alt="...">#}
                    <h2 class="text-center text-uppercase">
                        nos dernières annonces de rescapés à placer
                    </h2>
                    <br>
                {% for adoption in adoptions %}
                    {% include 'adoption/_adoption.html.twig' with {
                        adoption: adoption
                    } only %}
                {% endfor %}
                    {#<div class="row g-4">#}col-md-4 col-sm-12
                <div class="col-md-4 col-sm-12">

                {#{% for adoption in adoptions %}
                <div class="col-md-4 col-sm-12">
                    <div class="card shadow text-center">
                        <h2 class="card-header">
                            {{ adoption.name }}
                        </h2>
                    {% for dog in adoption.dogs %}
                        <div class="card-body">
                            <h3>
                                {{ dog.name }}
                                {% if dog.birthDate %}
                                    ({{ dog.age }} ans)
                                {% endif %}
                            </h3>#}
                                    {#<div class="row">
                                        {% for pictures in dog.pictures %}
                                            <img src="{{ image.path }}" class="col-6" alt="" style="height: auto">
                                        {% endfor %}
                                    </div>#}
                                   {# <div class="row">
                                        {% for breed in dog.breeds %}
                                            {{ breed.name }}
                                        {% endfor %}
                                    </div>
                                    <p class="card-text"></p>
                            {% endfor %}
                        </div>
                        <div class="card-footer">
                            <small class="text-muted">Cette annonce a été mise à jour le {{ adoption.updatedAt|date('d/m/Y à H:i') }}.</small>#}
                                   {# <a class="shadow" href="{{ path('default_contact_for_adoption', { id: adoption.id }) }}">
                                        Contacter ANIMA pour + d'infos
                                    </a>#}
                        {#</div>#}
                        {#<div class="card-footer text-muted">
                            Annonce mise à jour le
                        </div>#}
                    </div>
                </div>
                {#{% endfor %}#}

            </div>

                        <div>
                            <br>
                            <h2 class="text-center text-uppercase">
                                associations, SPA, vétérinaires et éleveurs ayant des rescapés à placer
                            </h2>
                            <br>
                            {% for association in associations %}
                            <div class="col-md-4 col-sm-12"></div>
                                <div class="row row-cols-1 row-cols-md-3 g-4">
                                    <div class="col">
                                        <div class="card h-100">
                                            ​<picture>
                                                {#<source srcset="images/home-header-Anima-img/chatons-psycho_61d46a6e8d925ecf4a5a25c62360bea8 1.svg" type="image/svg+xml">#}
                                                <img src="images/logo-anima/logo-vector.svg" class="img-fluid img-thumbnail" alt="...">
                                            </picture>
                                            <div class="card-body">
                                                <h5 class="card-title">
                                                    {{ association.name }}
                                                </h5>
                                                {% for adoption in association.adoption %}
                                                   {# TODO: CHANGER NOM POUR METTRE NOMBRE D ANNONCES POURVUS ET A POURVOIR#}
                                                <p class="card-text">{{ adoption.name }}</p>
                                                {% endfor %}
                                            </div>
                                            <div class="card-footer">
                                                <small class="text-muted">Last updated 3 mins ago</small>
                                            </div>
                                        </div>
                                    </div>
                                {% endfor %}
                            </div>
                        </div>

            </main>
       </body>

    {% endblock %}

templates/default/preadoption.html.twig
{% extends '/base.html.twig' %}

{% block title %}
    Formulaire de pré-adoption
{% endblock %}

{% block body %}

<section class="container shadow">
    ->add('firstname')
    ->add('lastname')
    ->add('phone')
    ->add('email')
    ->add('location', LocationType::class, [
    'data_class' => ContactPreAdoption::class,
    ])
    ->add('bithDate')
    ->add('adoption')
    ->add('description')
    ->add('association')
    ->add('createdAt')
    ->add('updatedAt')
    {{ form_start(form) }}
    {{ form_row(form.firstname, {
        label: 'Nom',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.lastname, {
        label: 'Nom',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.phone, {
        label: 'Téléphone',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.adoption, {
        label: 'Quelle animal souteriez-vous adopter?',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.email, {
        label: 'Votre adresse email',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.address, {
        label: 'Adresse',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.zipcode, {
        label: 'Code Postale',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.city, {
        label: 'Ville',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.country, {
        label: 'Pays',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    {{ form_row(form.bithDate, {
        label: 'Date de naissance',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}bithDate
    {{ form_row(form.message, {
        label: 'Votre message',
        row_attr: {
            class: 'mb-3',
        },
        label_attr: {
            class: 'form-label',
        },
        attr: {
            class: 'form-control',
        },
    }) }}
    <button type="submit" class="btn btn-info shadow">Envoyer</button>
    {{ form_end(form) }}

    <h2>
        Attention! Nous tenons à rappeler qu'une adoption est un acte qui doit être murement réfléchit,
        de nombreuses reponsabilités acompagnent...
        Vous donnez droit de visite à tous responsables de Anima, dans le cadre de l'accompagnement du placement
        de nos animaux rescapés.
        Anima se réserve le droit de reprendre un animal placé pour non respect de notre charte du bien être animal,
        dont vous aurez pris connaissance et signé (mauvais traitements, mal nourrit,
        mal souagné, ou vivant dans un espace non comforme).
    </h2>

    {% endblock %}